require('settings')
require('packer-config')
require('colorschemes-config')
require('mappings')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('nvim-tree-config')
require('lualine.lualine')
require('bufferline-config')
require('treesitter-config')
require('autopairs-config')
require('colorizer-config')
require('whichkey-config')
require('telescope-config')
require('gitsign-config')
require('dashboard-config')
require('blankline-config')
require('comment-config')


